version: '2'
services:

  web:
    container_name: api-web
    image: nginx:alpine
    ports:
      - "80:80"
    # environment:
    #   VIRTUAL_HOST: '${DOMAIN}'
    volumes:
      - ./web/conf.d:/etc/nginx/conf.d
      - ./logs:/var/log/nginx
    depends_on:
      - api
    restart: always
    networks:
      - proxy_net

  api:
    build:
      context: ./api
    image: ${IMAGE_NAME}:latest
    container_name: api-app
    expose:
      - 8000
    volumes:
      - ./api/app:/app/app
    mem_limit: ${MEM}
    restart: always
    networks:
      - proxy_net

networks:
  proxy_net:
    driver: bridge
    external: true