version: '3'
services:

  web:
    container_name: api-web
    image: nginx:alpine
    ports:
      - "$PORT_API:80"
    environment:
      VIRTUAL_HOST: '${DOMAIN}'
      TZ: 'Asia/Tokyo'
    volumes:
      - ./web/conf.d:/etc/nginx/conf.d
      - ./logs:/var/log/nginx
    depends_on:
      - api
    restart: always
    networks:
      - reactnet

  api:
    build:
      context: ./api
    image: ${IMAGE_NAME}:latest
    environment:
      TZ: 'Asia/Tokyo'
    container_name: api-app
    expose:
      - 8000
    volumes:
      - ./api/app:/app/app
    command: "uvicorn app.main:app --reload --host 0.0.0.0"
    mem_limit: ${MEM}
    restart: always
    networks:
      - reactnet

networks:
  reactnet:
    driver: bridge
    external: true